name: Build rootfs

on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * mon'

jobs:
  once:
    name: Generate Envs
    runs-on: ubuntu-latest
    outputs:
        timestamp: ${{ steps.get-timestamp.outputs.timestamp }}
    steps:
      - name: get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

  build-zip:
    name: Build zip file
    runs-on: ubuntu-latest
    needs: once
    steps:
      - name: Clone deepin-m1 repository 
        uses: actions/checkout@v2
      - name: Prepare keyring
        run: |
          wget https://community-packages.deepin.com/deepin/pool/main/d/deepin-keyring/deepin-keyring_2021.06.07.orig.tar.xz
          tar -xvf deepin-keyring_2021.06.07.orig.tar.xz
          sudo cp deepin-keyring-2021.06.07/keyrings/deepin-archive-camel-keyring.gpg /usr/share/keyrings/deepin-archive-camel-keyring.gpg
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install qemu qemu-user-static binfmt-support eatmydata debootstrap pigz
      - name: Prepare debootstrap script
        run: sudo cp /usr/share/debootstrap/scripts/bookworm /usr/share/debootstrap/scripts/beige
      - name: Skip zip steps for disk space
        run: sed -i "s/zip/#/g" bootstrap.sh
      - name: Build zip files
        run: bash bootstrap.sh
      - name: Upload deepin-desktop artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deepin-desktop-${{ needs.once.outputs.TIMESTAMP }}
          compression-level: 9
          path: build/aii/*
